'use client'

import Link from 'next/link'
import { ArrowDown, ArrowRight, ArrowUpRight, Box, Cpu, Database, Fingerprint, Layers3, LockKeyhole, Network, Orbit, Wallet } from 'lucide-react'
import { Button } from '@/components/ui/button'

const models = [
  { name: 'Vision Transformer XL', category: 'Computer vision', desc: 'High-resolution image classification with transparent, reproducible inference.', wallet: '0x71C7…4F2a', price: '0.18', format: 'ONNX', tint: 'cyan' },
  { name: 'Lumen Speech', category: 'Audio · Speech', desc: 'Natural speech synthesis tuned for expressive, low-latency voice generation.', wallet: '0xA93e…91D0', price: '0.24', format: 'PyTorch', tint: 'amber' },
  { name: 'Semantic Atlas', category: 'Language · Embeddings', desc: 'Compact multilingual embeddings for semantic search and retrieval.', wallet: '0x2bF1…C8e3', price: '0.08', format: 'Safetensors', tint: 'violet' },
]

function Header() {
  return <header className="site-header"><Link href="/" className="brand"><span className="brand-mark"><Orbit size={18}/></span><span><b>AI MARKETPLACE</b><small>/ @amandx36</small></span></Link><nav className="main-nav"><a href="#models">Explore</a><a href="#publish">Upload</a><Link href="/dashboard">Dashboard</Link><Link href="/transactions">Transactions</Link><a href="#architecture">Documentation</a></nav><Link href="/login"><Button className="wallet-button"><Wallet size={15}/> Connect Wallet</Button></Link></header>
}

function ModelCard({ model }: { model: typeof models[number] }) {
  return <article className="model-card"><div className={`model-art ${model.tint}`}><div className="art-orbit orbit-a"/><div className="art-orbit orbit-b"/><div className="art-core"><Cpu size={25}/></div><span className="ipfs-pill"><span/> IPFS PINNED</span></div><div className="model-body"><div className="flex items-center justify-between"><span className="category-pill">{model.category}</span><span className="chain-check"><span/> VERIFIED</span></div><h3>{model.name}</h3><p>{model.desc}</p><div className="model-meta"><span>CREATOR <b>{model.wallet}</b></span><span>FORMAT <b>{model.format}</b></span></div><div className="model-footer"><div><small>ACCESS PRICE</small><strong>{model.price} <i>ETH</i></strong></div><Link href="/models/vision-transformer-xl" className="model-link">View model <ArrowUpRight size={15}/></Link></div></div></article>
}

export default function Page() {
  return <main className="marketplace-shell"><Header/><section className="hero" id="top"><div className="hero-grid"/><div className="hero-copy"><div className="eyebrow"><span className="live-dot"/> THE OPEN MODEL ECONOMY <span className="eyebrow-line"/></div><h1>Own the Models.<br/><em>Own the Intelligence.</em></h1><p>A decentralized marketplace for discovering, buying, selling, and running AI models — powered by Ethereum, IPFS, and secure wallet authentication.</p><div className="hero-actions"><Link href="/explore"><Button className="button-primary">Explore Models <ArrowRight size={16}/></Button></Link><Link href="/upload"><Button variant="outline" className="button-secondary">Upload Your Model <ArrowUpRight size={15}/></Button></Link></div><div className="hero-proof"><span><LockKeyhole size={14}/> Wallet verified</span><span><Database size={14}/> IPFS storage</span><span><Network size={14}/> Ethereum settlement</span></div></div>
    <div className="hero-visual" aria-label="AI model cards connected through a decentralized network"><div className="visual-label"><span className="live-dot"/> MARKET NODE <b>0x7F…A921</b></div><div className="network-lines"><i/><i/><i/><i/><i/><i/></div><div className="node node-center"><div className="node-core"><Cpu size={30}/></div><b>MODEL<br/>NETWORK</b><small>ETHEREUM · MAINNET</small></div><div className="node node-ipfs"><Database size={17}/><span>IPFS<small>CONTENT ADDRESSED</small></span></div><div className="node node-wallet"><Fingerprint size={17}/><span>WALLET<small>OWNER VERIFIED</small></span></div><div className="node node-run"><Orbit size={17}/><span>INFERENCE<small>READY TO RUN</small></span></div><div className="floating-model"><div className="fm-top"><span className="model-mini-icon"><Layers3 size={16}/></span><span className="chain-check"><span/> ON CHAIN</span></div><small>FEATURED MODEL / 0042</small><b>Vision Transformer XL</b><span className="fm-bottom"><span>ONNX · IPFS</span><strong>0.18 ETH</strong></span></div><div className="visual-ring ring-one"/><div className="visual-ring ring-two"/><div className="visual-coordinates">37° 46′ 49.3″ N<br/>DECENTRALIZED INFERENCE LAYER</div></div><a href="#value" className="scroll-hint"><ArrowDown size={14}/> SCROLL TO EXPLORE</a></section>
    <section className="value-section" id="value"><div className="section-kicker">A MARKETPLACE WITH NO MIDDLEMAN <span>01 — THE PROTOCOL</span></div><div className="value-intro"><h2>Models are assets.<br/><em>Make them yours.</em></h2><p>Creators keep ownership. Buyers get verifiable access. Every model has a transparent path from storage to inference.</p></div><div className="value-grid">{[{n:'01',t:'Discover',d:'Explore AI/ML models published by developers across different categories.',icon:Network},{n:'02',t:'Own',d:'Model ownership, pricing, and access are backed by blockchain smart contracts.',icon:Fingerprint},{n:'03',t:'Run',d:'Purchase access and run inference directly through the platform.',icon:Cpu}].map(({n,t,d,icon:Icon})=><article className="value-card" key={n}><div className="value-card-top"><span>{n} / 03</span><Icon size={19}/></div><h3>{t}</h3><p>{d}</p><div className="value-underline"/></article>)}</div><div className="decentralized"><div><span className="section-kicker">TRUST MINIMIZED BY DESIGN</span><h3>Decentralized<br/><em>by design.</em></h3></div><div className="stack-list">{['Ethereum smart contracts','IPFS model storage','MetaMask wallet authentication','JWT-secured backend','FastAPI inference service'].map((item,i)=><div key={item}><span>0{i+1}</span>{item}<ArrowUpRight size={14}/></div>)}</div></div></section>
    <section className="models-section" id="models"><div className="section-kicker">OPEN MODEL EXCHANGE <span>02 — MARKETPLACE</span></div><div className="section-heading"><div><h2>Discover AI Models</h2><p>Find production-ready models, inspect details, verify ownership, and purchase access using ETH.</p></div><Link href="/explore" className="text-link">Explore marketplace <ArrowRight size={15}/></Link></div><div className="model-grid">{models.map(model=><ModelCard key={model.name} model={model}/>)}</div></section>
    <section className="publish-section" id="publish"><div className="publish-pattern"/><div className="publish-copy"><div className="section-kicker">BUILT BY YOU <span>03 — CREATOR ECONOMY</span></div><h2>Monetize Your<br/><em>Intelligence.</em></h2><p>Upload your trained model, store it on IPFS, register its ownership on-chain, set your price, and make it available to buyers.</p><Link href="/upload"><Button className="button-primary">Upload Model <ArrowRight size={16}/></Button></Link></div><div className="publish-flow">{[['01','MODEL FILE','ONNX · PT · PKL'],['02','IPFS STORAGE','CONTENT ADDRESSED'],['03','SMART CONTRACT','OWNERSHIP REGISTERED'],['04','MARKETPLACE','READY TO EARN']].map(([n,t,d])=><div className="flow-row" key={n}><span className="flow-number">{n}</span><div className="flow-icon"><Box size={17}/></div><div><b>{t}</b><small>{d}</small></div><span className="flow-state"><span/> READY</span></div>)}</div></section>
    <section className="how-section"><div className="section-kicker">FROM WALLET TO INFERENCE <span>04 — HOW IT WORKS</span></div><h2>Four steps. Full ownership.</h2><div className="steps-grid">{[['01','Connect','Connect your MetaMask wallet and authenticate through a signed message.'],['02','Publish','Upload your model → IPFS storage → blockchain registration → marketplace listing.'],['03','Purchase','Buy model access using ETH through the smart contract.'],['04','Run','Verify on-chain access and run the model through the inference service.']].map(([n,t,d])=><article className="step-card" key={n}><span>{n}</span><div className="step-line"/><h3>{t}</h3><p>{d}</p></article>)}</div></section>
    <section className="architecture" id="architecture"><div className="section-kicker">TRANSPARENT BY DEFAULT <span>05 — ARCHITECTURE</span></div><div className="architecture-heading"><h2>Built on a<br/><em>decentralized foundation.</em></h2><p>Each layer has a clear responsibility. Ownership and payments remain verifiable on-chain while inference stays one click away.</p></div><div className="architecture-map"><div className="arch-flow">{['Frontend','Spring Boot','Ethereum','IPFS','MongoDB','FastAPI'].map((name,i)=><div className="arch-item" key={name}><span className="arch-icon">{[<Orbit key="a"/>,<Network key="b"/>,<Fingerprint key="c"/>,<Database key="d"/>,<Layers3 key="e"/>,<Cpu key="f"/>][i]}</span><b>{name}</b>{i<5&&<ArrowRight className="arch-arrow" size={15}/>}</div>)}</div><div className="arch-details">{[['Ethereum','Ownership, access control, and ETH payments.'],['IPFS','Content-addressed storage for model files.'],['Spring Boot','APIs, authentication, and marketplace business logic.'],['MongoDB','Marketplace metadata and transaction records.'],['FastAPI','Model inference execution service.']].map(([t,d])=><div key={t}><b>{t}</b><span>{d}</span></div>)}</div></div></section>
    <footer className="site-footer"><Link href="/" className="brand"><span className="brand-mark"><Orbit size={18}/></span><span><b>AI MARKETPLACE</b><small>/ @amandx36</small></span></Link><span>OWN. TRADE. RUN. AI.</span><div><Link href="/explore">Explore</Link><Link href="/upload">Upload</Link><Link href="/dashboard">Dashboard</Link><Link href="/transactions">Transactions</Link></div></footer>
  </main>
}
