spring:
  application:
    name: aimarketplace

  data:
    mongodb:
      uri: mongodb://localhost:27017/aimarketplace

  output:
    ansi:
      enabled: ALWAYS

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 86000000
    refresh-expiration: 6480000

  cors:
    allowed-origin: http://localhost:3000,http://localhost:4200

server:
  port: 8000
  servlet:
    context-path: /api
  error:
    include-message: always
