
spring.application.name=aimarketplace


spring.data.mongodb.uri=${MONGODB_URI}


spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=60000


server.port=${SERVER_PORT:8000}
server.servlet.context-path=/api

server.error.include-message=always


spring.output.ansi.enabled=ALWAYS

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION}


cors.allowed-origin=${CORS_ALLOWED_ORIGINS}