spring:
  application:
    name: aimarketplace

  data:
    mongodb:
      host: localhost
      port: 27017
      database: ai-MarketPlace

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

# JWT settings
app:
  jwt:
    secret: djfdjdfjdfjdjfdkjdkfjsdfiouifiwskdfjksdss96950
    expiration-ms: 86000000
    refresh-expiration: 6480000

  cors:
    allowed-origin: http://localhost:3000,http://localhost:4200

server:
  port: 8000
  error:
    include-message: always
  servlet:
    context-path : /api